CREATE DATABASE IF NOT EXISTS `google_sheet_sync` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `google_sheet_sync`;
CREATE TABLE IF NOT EXISTS google_sheet_sync_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    trigger_type VARCHAR(80) NOT NULL DEFAULT 'manual',
    status VARCHAR(40) NOT NULL DEFAULT 'running',
    stats JSON NULL,
    error_message TEXT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY idx_google_sheet_sync_runs_status (status),
    KEY idx_google_sheet_sync_runs_started_at (started_at)
);
CREATE TABLE IF NOT EXISTS google_sheet_ar_int_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(255) NOT NULL,
    `date` DATE NULL,
    sr_no VARCHAR(80) NULL,
    broker_name VARCHAR(255) NULL,
    ppt_name VARCHAR(255) NULL,
    ppt_address TEXT NULL,
    ppt_number VARCHAR(120) NULL,
    en_number VARCHAR(120) NULL,
    ppt_issue_date DATE NULL,
    ppt_issue_place VARCHAR(255) NULL,
    ppt_expiry_date DATE NULL,
    dob DATE NULL,
    country VARCHAR(120) NULL,
    fe_number VARCHAR(255) NULL,
    dm_number VARCHAR(255) NULL,
    sponsor_phone_number VARCHAR(80) NULL,
    category VARCHAR(255) NULL,
    salary VARCHAR(120) NULL,
    sponsor_address TEXT NULL,
    sponsor_name VARCHAR(255) NULL,
    cr_number VARCHAR(255) NULL,
    jb_id VARCHAR(255) NULL,
    visa_issue_date DATE NULL,
    visa_expiry_date DATE NULL,
    visa_number VARCHAR(255) NULL,
    father_name VARCHAR(255) NULL,
    mother_name VARCHAR(255) NULL,
    legal_status VARCHAR(255) NULL,
    id_name VARCHAR(255) NULL,
    id_number VARCHAR(255) NULL,
    job_role VARCHAR(255) NULL,
    source_row_start INT NULL,
    source_row_end INT NULL,
    raw_data JSON NOT NULL,
    row_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_key (source_key),
    KEY idx_ppt_number (ppt_number),
    KEY idx_en_number (en_number),
    KEY idx_ppt_name (ppt_name),
    KEY idx_country (country),
    KEY idx_jb_id (jb_id),
    KEY idx_visa_number (visa_number),
    KEY idx_active (is_active),
    KEY idx_date (`date`)
);

CREATE TABLE IF NOT EXISTS google_sheet_royal_sky_int_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(255) NOT NULL,
    `date` DATE NULL,
    sr_no VARCHAR(80) NULL,
    broker_name VARCHAR(255) NULL,
    ppt_name VARCHAR(255) NULL,
    ppt_address TEXT NULL,
    ppt_number VARCHAR(120) NULL,
    en_number VARCHAR(120) NULL,
    ppt_issue_date DATE NULL,
    ppt_issue_place VARCHAR(255) NULL,
    ppt_expiry_date DATE NULL,
    dob DATE NULL,
    country VARCHAR(120) NULL,
    fe_number VARCHAR(255) NULL,
    dm_number VARCHAR(255) NULL,
    sponsor_phone_number VARCHAR(80) NULL,
    category VARCHAR(255) NULL,
    salary VARCHAR(120) NULL,
    sponsor_address TEXT NULL,
    sponsor_name VARCHAR(255) NULL,
    cr_number VARCHAR(255) NULL,
    jb_id VARCHAR(255) NULL,
    visa_issue_date DATE NULL,
    visa_expiry_date DATE NULL,
    visa_number VARCHAR(255) NULL,
    father_name VARCHAR(255) NULL,
    mother_name VARCHAR(255) NULL,
    legal_status VARCHAR(255) NULL,
    id_name VARCHAR(255) NULL,
    id_number VARCHAR(255) NULL,
    job_role VARCHAR(255) NULL,
    source_row_start INT NULL,
    source_row_end INT NULL,
    raw_data JSON NOT NULL,
    row_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_key (source_key),
    KEY idx_ppt_number (ppt_number),
    KEY idx_en_number (en_number),
    KEY idx_ppt_name (ppt_name),
    KEY idx_country (country),
    KEY idx_jb_id (jb_id),
    KEY idx_visa_number (visa_number),
    KEY idx_active (is_active),
    KEY idx_date (`date`)
);

CREATE TABLE IF NOT EXISTS google_sheet_vivan_2024_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(255) NOT NULL,
    `date` DATE NULL,
    sr_no VARCHAR(80) NULL,
    broker_name VARCHAR(255) NULL,
    ppt_name VARCHAR(255) NULL,
    ppt_address TEXT NULL,
    ppt_number VARCHAR(120) NULL,
    en_number VARCHAR(120) NULL,
    ppt_issue_date DATE NULL,
    ppt_issue_place VARCHAR(255) NULL,
    ppt_expiry_date DATE NULL,
    dob DATE NULL,
    country VARCHAR(120) NULL,
    fe_number VARCHAR(255) NULL,
    dm_number VARCHAR(255) NULL,
    sponsor_phone_number VARCHAR(80) NULL,
    category VARCHAR(255) NULL,
    salary VARCHAR(120) NULL,
    sponsor_address TEXT NULL,
    sponsor_name VARCHAR(255) NULL,
    cr_number VARCHAR(255) NULL,
    jb_id VARCHAR(255) NULL,
    visa_issue_date DATE NULL,
    visa_expiry_date DATE NULL,
    visa_number VARCHAR(255) NULL,
    father_name VARCHAR(255) NULL,
    mother_name VARCHAR(255) NULL,
    legal_status VARCHAR(255) NULL,
    id_name VARCHAR(255) NULL,
    id_number VARCHAR(255) NULL,
    job_role VARCHAR(255) NULL,
    source_row_start INT NULL,
    source_row_end INT NULL,
    raw_data JSON NOT NULL,
    row_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_key (source_key),
    KEY idx_ppt_number (ppt_number),
    KEY idx_en_number (en_number),
    KEY idx_ppt_name (ppt_name),
    KEY idx_country (country),
    KEY idx_jb_id (jb_id),
    KEY idx_visa_number (visa_number),
    KEY idx_active (is_active),
    KEY idx_date (`date`)
);

CREATE TABLE IF NOT EXISTS google_sheet_sns_global_service_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(255) NOT NULL,
    `date` DATE NULL,
    sr_no VARCHAR(80) NULL,
    broker_name VARCHAR(255) NULL,
    ppt_name VARCHAR(255) NULL,
    ppt_address TEXT NULL,
    ppt_number VARCHAR(120) NULL,
    en_number VARCHAR(120) NULL,
    ppt_issue_date DATE NULL,
    ppt_issue_place VARCHAR(255) NULL,
    ppt_expiry_date DATE NULL,
    dob DATE NULL,
    country VARCHAR(120) NULL,
    fe_number VARCHAR(255) NULL,
    dm_number VARCHAR(255) NULL,
    sponsor_phone_number VARCHAR(80) NULL,
    category VARCHAR(255) NULL,
    salary VARCHAR(120) NULL,
    sponsor_address TEXT NULL,
    sponsor_name VARCHAR(255) NULL,
    cr_number VARCHAR(255) NULL,
    jb_id VARCHAR(255) NULL,
    visa_issue_date DATE NULL,
    visa_expiry_date DATE NULL,
    visa_number VARCHAR(255) NULL,
    father_name VARCHAR(255) NULL,
    mother_name VARCHAR(255) NULL,
    legal_status VARCHAR(255) NULL,
    id_name VARCHAR(255) NULL,
    id_number VARCHAR(255) NULL,
    job_role VARCHAR(255) NULL,
    source_row_start INT NULL,
    source_row_end INT NULL,
    raw_data JSON NOT NULL,
    row_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_key (source_key),
    KEY idx_ppt_number (ppt_number),
    KEY idx_en_number (en_number),
    KEY idx_ppt_name (ppt_name),
    KEY idx_country (country),
    KEY idx_jb_id (jb_id),
    KEY idx_visa_number (visa_number),
    KEY idx_active (is_active),
    KEY idx_date (`date`)
);

CREATE TABLE IF NOT EXISTS google_sheet_greenvally_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key VARCHAR(255) NOT NULL,
    `date` DATE NULL,
    sr_no VARCHAR(80) NULL,
    broker_name VARCHAR(255) NULL,
    ppt_name VARCHAR(255) NULL,
    ppt_address TEXT NULL,
    ppt_number VARCHAR(120) NULL,
    en_number VARCHAR(120) NULL,
    ppt_issue_date DATE NULL,
    ppt_issue_place VARCHAR(255) NULL,
    ppt_expiry_date DATE NULL,
    dob DATE NULL,
    country VARCHAR(120) NULL,
    fe_number VARCHAR(255) NULL,
    dm_number VARCHAR(255) NULL,
    sponsor_phone_number VARCHAR(80) NULL,
    category VARCHAR(255) NULL,
    salary VARCHAR(120) NULL,
    sponsor_address TEXT NULL,
    sponsor_name VARCHAR(255) NULL,
    cr_number VARCHAR(255) NULL,
    jb_id VARCHAR(255) NULL,
    visa_issue_date DATE NULL,
    visa_expiry_date DATE NULL,
    visa_number VARCHAR(255) NULL,
    father_name VARCHAR(255) NULL,
    mother_name VARCHAR(255) NULL,
    legal_status VARCHAR(255) NULL,
    id_name VARCHAR(255) NULL,
    id_number VARCHAR(255) NULL,
    job_role VARCHAR(255) NULL,
    source_row_start INT NULL,
    source_row_end INT NULL,
    raw_data JSON NOT NULL,
    row_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_key (source_key),
    KEY idx_ppt_number (ppt_number),
    KEY idx_en_number (en_number),
    KEY idx_ppt_name (ppt_name),
    KEY idx_country (country),
    KEY idx_jb_id (jb_id),
    KEY idx_visa_number (visa_number),
    KEY idx_active (is_active),
    KEY idx_date (`date`)
);


